### ISSUE TITLE
Refactoring PR

### ISSUE THREAD

**Issue by hyeokjunejeon** [furiosa-ai/furiosa-artifacts#27]
코드 추가 및 기존 것을 제거하다보니, 향후 없어질 코드들이 발생할 듯 합니다.
MobileResnet34 까지하면 코드 리팩토링를 고려 중이 었습니다.

하지만, @ileixe 혹시, Yolo 하는 데 영향이 갈 수 있을 듯 해요, Yolo이후에 하는 것은 어떤까요?

**Comment by ileixe** [comment]
yolo랑 공통코드가 없을거 같아서요, 없앨코드는 먼저 없애주시는게 오히려 도움이 될 거 같습니다 감사합니다!

**Comment by hyeokjunejeon** [comment]
#36
