### ISSUE TITLE
Model Zoo API 리펙토링

### ISSUE THREAD

**Issue by hyunsik** [furiosa-ai/furiosa-artifacts#48]
* preprocess 는 image binary 를 받을 수 있도록 수정
  * 현재는 file path 를 입력 받아 I/O 수행 시간이 수반됨
* preprocess/postprocess 클래스 멤버 변수에서 module내의 함수로 이동
  * 재사용성 높일 수 있으며 preprocess/postprocess 호출을 위해 모델 이미지 다운로드 받을 필요 없음
* label 등 모델에 의존적인 데이터는 module 내의 상수로 이동 
* Image classification의 pre/post process API 리펙토링
  * preprocess(bytes_or_path)
    * 필요하면, crop 위치나 기타 이미지 관련 파라메터 추가
  * ArgMax가 안 붙은 모델의 경우 `postprocess(model_output, top: int = 1) -> List[Tuple[string, float]]`
    * Top-k label and score 리스트를 출력하도록 개선
  * ArgMax가 붙은 모델의 경우 `postprocess(model_output) -> str`
     *  현재 ResNet50은 이 경우에 해당하므로 변경 사항 없음
* Object detection의 pre/post process API 리펙토링 (@hyeokjunejeon)
  * preprocess(bytes_or_path)
    * 필요하면, crop 위치나 기타 이미지 관련 파라메터 추가
  * postprocess(model_output, top: int = 1) -> List[Tuple[string, float, List[float]] (class label, score, bounding box)
    * mlcommons의 post processing 결과 ([DetectionResult](https://github.com/furiosa-ai/mlcommons/blob/60253f5e59cc826b63a3f2278766c669479ab3f5/mlperf/src/common/ssd_postprocess.rs#L162))를 특별한 변환 없이 사용할 수 있도록 변경
    * 현재 리턴 값은 `Tuple[List[np.ndarray], List[np.ndarray], List[np.ndarray]]`으로 제안한 API 가 더 직관적

**Comment by hyeokjunejeon** [comment]
@hyunsik 님, 단순 파일을 읽는 부분을 제외하면, preprocess() 부분은 변경의 여지를 주지 않는 것이 좋을 듯합니다. 조금이라도 변경하면, 모델 정확도는 보장할 수 없습니다.

**Comment by hyunsik** [comment]
혁준님 주신 코멘트에 대해서는 구두로 논의 했으며 file에서 image를 로딩하는 함수는 furiosa.models.vision.preprocess 에 넣고 공용으로 사용하기로 했습니다.
